{
 "title": "Gravitate Health Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "FOSPS Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Focusing Manager",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{service_name=\"focusing-manager\"}"
    }
   ]
  },
  {
   "title": "Chatbot Interface",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{service_name=\"chatbot-interface\"}"
    }
   ]
  },
  {
   "title": "Keycloak Registration",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{service_name=\"keycloak-registration\"}"
    }
   ]
  },
  {
   "title": "Lens Selector MVP2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{service_name=\"lens-selector-mvp2\"}"
    }
   ]
  },
  { "title": "Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Ingress Gateway",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{service_name=\"istio-ingressgateway\"}"
    }
   ]
  },
  {
   "title": "Kube System Namespace",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"kube-system\"}"
    }
   ]
  },
  {
   "title": "MetalLB Namespace",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{namespace=\"metallb-system\"}"
    }
   ]
  }
 ]
}