deploymentMode: SingleBinary
global:
  dnsService: coredns
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  extraArgs:
    server.path-prefix: /loki/
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem # we're storing on filesystem so there's no real persistence here.
      schema: v13
singleBinary:
  replicas: 1
  persistence:
    size: 10Gi
chunksCache:
  enabled: false
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0