repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  createNamespace: true
  wait: true
  timeout: 600

releases:
  - name: monitor-routing
    namespace: monitoring
    chart: ./helm/charts/monitor-routing
    values:
      - virtualService:
          hosts:
            - "*"
          gateway: default/gh-gateway

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - helm/values/prometheus.yaml.gotmpl

  - name: loki
    namespace: monitoring
    chart: grafana/loki
    values:
      - helm/values/loki.yaml

  - name: promtail
    namespace: monitoring
    chart: grafana/promtail
    values:
      - helm/values/promtail.yaml

  - name: prometheus-blackbox-exporter
    namespace: monitoring
    chart: prometheus-community/prometheus-blackbox-exporter
    values:
      - helm/values/blackbox-exporter.yaml

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - helm/values/grafana.yaml.gotmpl
