{
 "title": "gh-monit",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bundleId", "label": "bundleId", "query": { "query": "label_values(bundleId)" } },
   { "name": "patientId", "label": "patientId", "query": { "query": "label_values(patientId)" } },
   { "name": "language", "label": "language", "query": { "query": "label_values(language)" } },
   { "name": "preprocessMethod", "label": "preprocessMethod", "query": { "query": "label_values(preprocessMethod)" } },
   { "name": "lens", "label": "lens", "query": { "query": "label_values(lens)" } }
  ]
 },
 "panels": [
  { "title": "Filtered queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filter Queries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"gh_monit\", __name__!=\"push_time_seconds\", bundleId=~\"$bundleId\", patientId=~\"$patientId\", language=~\"$language\", preprocessMethod=~\"$preprocessMethod\", lens=~\"$lens\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "All Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"gh_monit\", __name__!=\"push_time_seconds\"} != 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"gh_monit\", __name__!=\"push_time_seconds\"} == 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "All queries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"gh_monit\", __name__!=\"push_time_seconds\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}