extraScrapeConfigs: |
  - job_name: questdb
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - questdb.default.svc.cluster.local:9003
server:
  baseUrl: https://gravitate-health.lst.tfo.upm.es/prometheus/
  prefixURL: /prometheus

  extraFlags:
  - web.external-url=https://gravitate-health.lst.tfo.upm.es/prometheus