
persistence:
  enabled: true
  size: 10Gi
env:
  GF_SERVER_ROOT_URL: "https://fosps.gravitatehealth.eu/grafana/"
grafana.ini:
  log:
    mode: console
    level: debug
  server:
    domain: fosps.gravitatehealth.eu
    root_url: https://fosps.gravitatehealth.eu/grafana
    serve_from_sub_path: true
    enforce_domain: true
  auth:
    basicAuth:
      enabled: true
datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server/prometheus
      access: proxy
      isDefault: true

    - name: Loki
      type: loki
      url: http://loki-gateway
      access: proxy
      isDefault: false
plugins:
  #- yesoreyeram-infinity-datasource
dashboardsConfigMaps:
  gh: grafana-dashboards-gh
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
    - name: 'gh'
      orgId: 1
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/gh
dashboards:
  #gh:
  #  gh-monit:
  #    file: gh-monit.json
  #  gh-logs:
  #    file: gh-logs.json
  default:
    kubernetes-views-pods:
       gnetId: 15760
       revision: 34
       datasource: Prometheus
    kubernetes-cluster-monitoring:
        gnetId: 315
        revision: 3
        datasource: Prometheus
